version: '3.8'

services:
  api:
    build: ./simple_api
    container_name: student_api
    ports:
      - "5000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - student_network

  web:
    image: php:apache
    container_name: student_web
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    depends_on:
      - api
    networks:
      - student_network

networks:
  student_network:
   driver: bridge
  
